config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'users', 
    controllers: { sessions: "users/sessions", 
    passwords: 'users/passwords',
    registrations: "users/registrations" }
  resources :users, only: [:show]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :study_records do
    collection do
      post :master
    end
  end
  resources :answers
  resources :study_sets
  resources :sources
  resources :links do
  	resources :entries, controller: 'links/entries'  	
  end
  resources :clicks
  resources :user_settings

  root to: "links#index"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/study_set.rb
class StudySet < ApplicationRecord
	belongs_to :user
	belongs_to :link
	has_and_belongs_to_many :entries, before_add: :add_study_record
	has_many :study_records, through: :entries

	def add_study_record(entry)
		StudyRecord.create(user: user, entry: entry, due: Time.now).save
		true
	end

end

app/controllers/study_sets_controller.rb
class StudySetsController < ApplicationController
  include Devise::Controllers::Helpers 
  before_action :authenticate_user!
  before_action :set_study_set, only: [:show, :edit, :update, :destroy]
  before_action :set_extra_answers, only: [:index, :show]

  # GET /study_sets
  # GET /study_sets.json
  def index
     respond_to do |format|
      format.html { render 'show' }

      # add details here!
      format.json { render json: { :part_of_set => json_params_for(Entry.joins(:study_records).where("study_records.due < ?", Time.now)),  
        :extra_answers => @extra_answers } }
    end 
  end

  # GET /study_sets/1
  # GET /study_sets/1.json
  def show
    @article_link = @study_set.link.url

    respond_to do |format|
      format.html
      format.json { render json: { :part_of_set => json_params_for(@study_set.entries.joins(:study_records).where("study_records.due < ?", Time.now)),  
        :extra_answers => @extra_answers } }
    end
  end

  # @study_set.study_records.entries.where("study_records.due < ?", Time.now)

  # GET /study_sets/new
  def new
    @study_set = StudySet.new
  end

  # GET /study_sets/1/edit
  def edit
  end

  # POST /study_sets
  # POST /study_sets.json
  def create
    @study_set = StudySet.new(user_id: current_user.id, link_id: params[:study_set][:link_id])
    @study_set.entries << Entry.find(params[:study_set][:entry_id])

    respond_to do |format|
      if @study_set.save
        if params.has_key? 'save-return'
          format.html { redirect_to current_user, notice: 'Study set was successfully created.'  }
        else
          format.html { redirect_to @study_set, notice: 'Study set was successfully created.' }
          format.json { render json: @study_set.entries }
        end
      else
        format.html { render :new }
        format.json { render json: @study_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /study_sets/1
  # PATCH/PUT /study_sets/1.json
  def update
    @new_entries = params[:study_set][:entry_id] - @study_set.entry_ids
    @study_set.entry_ids = params[:study_set][:entry_id]
    respond_to do |format|
      if !@study_set.errors.present?
        if params.has_key? 'save-return'
          format.html { redirect_to current_user, notice: 'Study set was successfully updated.'  }
        else
          format.html { redirect_to @study_set, notice: 'Study set was successfully updated.' }
          format.json { render :show, status: :ok, location: @study_set }
        end
      else
        format.html { render :edit }
        format.json { render json: @study_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /study_sets/1
  # DELETE /study_sets/1.json
  def destroy
    @study_set.destroy
    respond_to do |format|
      format.html { redirect_to study_sets_url, notice: 'Study set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study_set
      @study_set = StudySet.find(params[:id])
    end

    def set_extra_answers
      # This should be replaced with words the user knows in the future.
      @extra_answers = Entry.order(Arel.sql('RAND()')).take(5)
    end

    # Only allow a list of trusted parameters through.
    def study_set_params
      params.require(:study_set).permit(:return, :user_id, :link_id, :entry_id => [] )
    end

    def json_params_for(entries)
      collection = entries.map do |entry|
        { id: entry.id,
          word: entry.word,
          reading: entry.reading,
          definition: entry.definition,
          priority: entry.priority,
          base_word: entry.base_word,
          grammar: entry.grammar,
          mastery: entry.study_records.find_by(user: current_user).mastery
        }
      end
    end

end

app/helpers/study_sets_helper.rb
module StudySetsHelper
end

app/views/study_sets/_form.html.erb
<%= form_with(model: study_set, local: true) do |form| %>
  <% if study_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(study_set.errors.count, "error") %> prohibited this study_set from being saved:</h2>

      <ul>
        <% study_set.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :link_id %>
    <%= form.number_field :link_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/study_sets/edit.html.erb
<h1>Editing Study Set</h1>

<%= render 'form', study_set: @study_set %>

<%= link_to 'Show', @study_set %> |
<%= link_to 'Back', study_sets_path %>

app/views/study_sets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Study Sets</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @study_sets.each do |study_set| %>
      <tr>
        <td><%= study_set.user_id %></td>
        <td><%= study_set.link_id %></td>
        <td><%= link_to 'Show', study_set %></td>
        <td><%= link_to 'Edit', edit_study_set_path(study_set) %></td>
        <td><%= link_to 'Destroy', study_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Study Set', new_study_set_path %>

app/views/study_sets/new.html.erb
<h1>New Study Set</h1>

<%= render 'form', study_set: @study_set %>

<%= link_to 'Back', study_sets_path %>

app/views/study_sets/show.html.erb
<div id="card" class="flash-card card-container" style="display: none;">
  <div class="front card-inner standard-shadow">
    <div class="vert-center">
      <h4><b id="japanese-word"></b></h4>
      <p id="japanese-reading"></p>
    </div>
  </div>  
   <div class="back card-inner standard-shadow">
     <div class="vert-center definition">
    <p id="english-def"></p>
    </div>
  </div>  
</div>

<div class="prompt-container card-container" style="display: none;">
  <div class="prompt standard-shadow">
    <div class="vert-center">
      <h4 id="prompt"></h4>
      <p id="prompt-reading"></p>
    </div>
  </div>

</div>
<div class="answers card-container" style="display: none;">
  <div id="answer0" class="answer standard-shadow">
    <a href="#"></a>
  </div>
  <div id="answer1" class="answer standard-shadow">
    <a href="#"></a>
  </div>
  <div id="answer2" class="answer standard-shadow">
    <a href="#"></a>
  </div>
  <div id="answer3" class="answer standard-shadow">
    <a href="#"></a>
  </div>
</div>
<div id="showable-box" class="button-box" style="display: none;">
  <div id="flip-card-button" class="flip-card-container">
    <span class="card-button">Flip Card</span>
  </div>
  <div id="next-card-button" class="flip-card-container">
    <span class="card-button">Next Card</span>
  </div>
</div>

<div id="nextq-box" class="button-box" style="display: none;">
  <div id="next-question" class="sb-container">
    <span class="card-button">Next Question</span>
  </div>
</div>

<div class="results-container card-container" style="display: none;">
  <div class="results standard-shadow">
    <div class="vert-center">
      <h2>Finished learning!</h2>
      <b>Accuracy:</b> <span id="accuracy"></span>
    </div>
  </div>  
</div>

<div id="read-box" class="button-box" style="display: none;">
  <div id="back-button" class="sb-container">
    <a href="<%= user_path(current_user) %>" class="card-button">Back to Dashboard</a>
  </div>
  <% if !@article_link.nil? %>
    <div id="read-button" class="sb-container">
      <a href="<%= @article_link %>" class="card-button">Read Article</a>
    </div>
  <% end %>
</div>
<%= javascript_pack_tag 'quiz-controller', 'data-turbolinks-track': 'reload' %>