config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'users', 
    controllers: { sessions: "users/sessions", 
    passwords: 'users/passwords',
    registrations: "users/registrations" }
  resources :users, only: [:show]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :study_records do
    collection do
      post :master
    end
  end
  resources :answers
  resources :study_sets
  resources :sources
  resources :links do
  	resources :entries, controller: 'links/entries'  	
  end
  resources :clicks
  resources :user_settings

  root to: "links#index"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/entry.rb
class Entry < ApplicationRecord
	has_and_belongs_to_many :links
	has_and_belongs_to_many :study_sets
	has_many :study_records
	has_many :secondaries, class_name: "Entry", foreign_key: "primary_id"
	belongs_to :primary, class_name: "Entry", optional: true
	validates_presence_of :base_word, :word, :reading, :definition 
end

app/models/link.rb
class Link < ApplicationRecord
	belongs_to :source
  	has_many :clicks
  	has_many :users, through: :clicks
  	has_and_belongs_to_many :entries
  	has_many :study_sets
  	has_many :study_records, through: :study_sets

  	validates_presence_of :title
  	validates :url, url: { schemes: ['https', 'http'] }

  	scope :ordered_by_newest, -> { order(created_at: :desc) }
end

app/controllers/links/entries_controller.rb
module Links
  class EntriesController < ApplicationController
    before_action :set_entry, only: [:show, :edit, :update, :destroy]
    before_action :set_link
    load_and_authorize_resource

    # GET /entries
    # GET /entries.json
    def index

      # First grab the study_set so that we make sure not to filter out words that are in this study set
      @study_set = @link.study_sets.find_or_initialize_by(user: current_user)      

      # Filter out known words from other study sets.
      known_entries = current_user.entries.select(:base_word).where.not(base_word: @study_set.entries.pluck(:base_word)).pluck(:base_word)
      known_entries = known_entries + current_user.entries.deleted.pluck(:base_word)
    #  pry
      @priority_entries = @link.entries.where(grammar: false, priority: true, primary_id: nil).where.not(base_word: known_entries)
      filtered_entries = known_entries + @priority_entries.pluck(:base_word)
      @entries = @link.entries.where(grammar: false, priority: false, primary_id: nil).where.not(base_word: filtered_entries)
      @grammar_entries = @link.entries.where(grammar: true, primary_id: nil).where.not(base_word: known_entries)

    end

    # GET /entries/1
    # GET /entries/1.json
    def show
    end

    # GET /entries/new
    def new
      @entry = Entry.new
    end

    # GET /entries/1/edit
    def edit
      respond_to do |format|
        format.html {}
        format.js
      end

    end

    # POST /entries
    # POST /entries.json
    def create
      @entry = Entry.new(entry_params)

      respond_to do |format|
        if @entry.save
          format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
          format.json { render :show, status: :created, location: @entry }
        else
          format.html { render :new }
          format.json { render json: @entry.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /entries/1
    # PATCH/PUT /entries/1.json
    def update   
      respond_to do |format|
        if @entry.update(entry_params)
          format.html { redirect_to link_entries_path(@link), notice: 'Entry was successfully updated.' }
          format.js { redirect_to link_entries_path(@link)}
          format.json { render :show, status: :ok, location: @entry }
        else
          format.html { render :edit }
          format.json { render json: @entry.errors, status: :unprocessable_entity }
        end
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_entry
        @entry = Entry.find(params[:id])
      end

      def set_link
        @link = Link.find(params[:link_id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def entry_params
        params.require(:entry).permit(:word, :reading, :definition, :priority, :base_word, :grammar, :deleted)
      end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, :only => [:index]

  # GET /links
  # GET /links.json
  def index
    @links = Link.left_joins(:clicks).group(:id).where('links.created_at >= ?', 1.week.ago)
      .order('links.created_at  DESC, SUM(click_count) DESC').first(12)
    puts 
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: user_path(current_user), notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url, :descrip, :image, :source_id)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/entries/_entry_table.html.erb
<div class="tab">
	<input type="radio" id="rd<%= tab_num%>" name="rd" <%= checked ? "checked" : "" %>>
	<label class="tab-label" for="rd<%= tab_num%>">	
		<div class="toggle-switch">
			<%= tab_name %>
			<input type="checkbox" id="<%= table_name %>_switch" name="select_all" <%= checked ? "checked" : "" %>><label for="<%= table_name %>_switch">Toggle</label></input>	
		</div>
	</label>

	<div class=" tab-content">
		<table class="<%= table_name %>">
			<thead>
			  <tr>
			    <th>Study</th>
			    <th colspan="2">Word</th>
			    <th>Definition</th>
			    <th></th>
			    <th></th>
			    <% if can? :edit, Entry %>
			    	<th></th>
			    <% end %>
			  </tr>
			</thead>
			<tbody>
			  <% entries.each do |entry| %>
			    <tr id="entry-<%= entry.id %>">
			    	<td><%= check_box_tag 'study_set[entry_id][]', entry.id, (@study_set.id.nil? ? checked : (@study_set.entries.exists?(entry.id) ? true : false)), id: "study_set_#{entry.id}" %></td>
			   	<!-- If the reading is different from the base word, the base word probably has kanji and needs a tooltip that displays it. -->
			    <td colspan="2" class="word">
				    <% if entry.base_word == entry.reading %>
				      <%= entry.base_word %>
				    <% else %>			    
				      <span class="tooltip"><%= entry.base_word %><span class="tooltiptext"><%= entry.reading %></span></span>
				    <% end %>
				</td>
			      <td><%= entry.definition %><%= entry.secondaries.count > 0 ? raw(" (<span class='alt-tab' id='tab-#{entry.id}'>Alternative definitions</span>)") : "" %></td>
			      <td><%= link_to 'Master', master_study_records_path(study_record: {entry_id: entry.id}), 
			      	method: :post, class: "master_entry_link", tabindex: '0', 
			      	data: { entryid: entry.id} , remote: true %></td>
			      <% if can? :edit, Entry %>
			      	<td><%= link_to 'Edit', edit_link_entry_path(@link.id, entry), remote: true, class: "edit_entry_link" %></td>
			      <% end %>
			    </tr>
			    <% if entry.secondaries.count > 0 %>
			    	<% entry.secondaries.each do |entry| %>

			    		<tr class="tab-alt-content nav-<%= entry.primary_id %>" id="entry-<%= entry.id %>">
							<td></td>
							<td><%= check_box_tag 'study_set[entry_id][]', entry.id, (@study_set.entries.exists?(entry.id) ? true : false), id: "study_set_#{entry.id}" %></td>
							<td>				    
								<% if entry.base_word == entry.reading %>
				      				<%= entry.base_word %>
				    			<% else %>			    
				      				<span class="tooltip"><%= entry.base_word %><span class="tooltiptext"><%= entry.reading %></span></span>
				    			<% end %>
				    		</td>
							<td><%= entry.definition %></td>
							<td><a data-entry-id="<%= entry.id %>" class="master_entry_link" tabindex="0">Master</a></td>
							<% if can? :edit, Entry %>
			      				<td><%= link_to 'Edit', edit_link_entry_path(@link.id, entry), remote: true, class: "edit_entry_link" %></td>
			      			<% end %>
						</tr>
					
			    	<% end %>
				<% end %>
			  <% end %>
			</tbody>
		</table>
	</div>
</div>


app/views/links/entries/_form.html.erb
<%= form_for [@link, @entry], :remote => true, html: {id: :ajax_entry_form } do |form| %>
<input type=hidden name="authenticity_token" value="<%= form_authenticity_token %>">
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% @entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<ul class="entry-form">
  <li class="field">
    <%= form.label :word %>
    <%= form.text_field :word %>
  </li>

  <li class="field">
    <%= form.label :reading %>
    <%= form.text_field :reading %>
  </li>

  <li class="field">
    <%= form.label :definition %>
    <%= form.text_area :definition %>
  </li>

  <li class="field field-boxes">
    <%= form.label :priority do %>
      <%= form.check_box :priority %>
      <span>Priority</span>
    <% end %>
    <%= form.label :grammar do  %>
      <%= form.check_box :grammar  %>
      <span>Grammar</span>
    <% end %>
  </li>

  <li class="actions">
    <%= form.submit %>
  </li>
<% end %>

app/views/links/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/links/entries/edit.js.erb
console.log("#entry-<%= @entry.id %>")

if ($('#edit_entry_form_row').length) {
	$('#edit_entry_form_row td').wrapInner('<div style="display: block;" />').parent().find('td > div').slideUp(400, function() {
		$(this).parent().parent().remove();
		insertForm();
	});
} else {
	insertForm();
}

function insertForm() {
	$('<tr id="edit_entry_form_row"><td colspan="4"><%= j (render partial: "form") %></td></tr>').insertAfter('#entry-<%= @entry.id %>');
	$('#edit_entry_form_row td').wrapInner('<div style="display: none;" />').parent().find('td > div').slideDown(700, function() {
		var $set = $(this);
		$set.replaceWith($set.contents());
	});	
};



app/views/links/entries/index.html.erb
<div id="entries-container">

  <p id="notice"><%= notice %></p>
<%= form_for @study_set do |f| %>
<%= f.hidden_field :link_id, :value => @link.id %>
  <div class="entry-top-bar">
    <div class="entry-col1">
      <% if params[:edit] %>
        <%= f.submit 'Save & Return', :class => 'learn-read', :name => 'save-return' %>
      <% end %>
    </div>
    <div class="entry-col2"><h1>Vocabulary for this Article</h1></div>
    <div class="entry-col3"><%= f.submit 'Learn & Read', :class => 'learn-read', :name => 'learn-read' %></div>
  </div>

  <%= render partial: "entry_table", locals: {table_name: "article-words", entries: @entries, tab_name: "Difficult Words", tab_num: "1", checked: true} %> 

  <%= render partial: "entry_table", locals: {table_name: "priority-words", entries: @priority_entries, tab_name: "Common Words", tab_num: "2", checked: false} %> 

  <%= render partial: "entry_table", locals: {table_name: "grammar-words", entries: @grammar_entries, tab_name: "Grammar Points", tab_num: "3", checked: false} %> 
<% end %>
  <br>
</div>

<%= javascript_pack_tag 'tab-state-maintainer', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'box-checker', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'alt-tab-shower', 'data-turbolinks-track': 'reload' %>
<% if current_user.is_master_warning_showable %>
  <%= javascript_pack_tag 'confirm-master', 'data-turbolinks-track': 'reload' %>
<% end %>

app/views/links/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

app/views/links/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @entry.word %>
</p>

<p>
  <strong>Reading:</strong>
  <%= @entry.reading %>
</p>

<p>
  <strong>Def:</strong>
  <%= @entry.def %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @entry.priority %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>