config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'users', 
    controllers: { sessions: "users/sessions", 
    passwords: 'users/passwords',
    registrations: "users/registrations" }
  resources :users, only: [:show]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :study_records do
    collection do
      post :master
    end
  end
  resources :answers
  resources :study_sets
  resources :sources
  resources :links do
  	resources :entries, controller: 'links/entries'  	
  end
  resources :clicks
  resources :user_settings

  root to: "links#index"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :clicks
  has_many :links, through: :clicks
  has_many :study_sets
  has_many :study_records
  has_many :user_settings
  has_many :entries, through: :study_records do 
  	def deleted(order = "study_records.updated_at DESC")
      where("study_records.deleted = ?", true).order(order)
  	end
  end

  include Gravtastic
  gravtastic :secure => true,
    :default => "mm"

  after_create :default_settings

  def is_master_warning_showable 
    self.user_settings.find_by(setting_id: 1).unconstrained_value == "true"
  end

  private
    def default_settings
      @user = User.last
      # by default show warnings when user masters a word
      @user.user_settings.create!(setting_id: 1, unconstrained_value: "true", allowed_setting_value: nil)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Devise::Controllers::Helpers 
  include Pagy::Backend
  before_action :authenticate_user!
  layout 'userdash'

  def new
  end

  def show
   	@total_words = current_user.study_records.count
   	@article_count = current_user.links.count
    sort = params[:sort]
    sort = 'updated_at DESC' unless sort.in?(['study_records.updated_at DESC', 'study_records.updated_at ASC'])
   	if params[:tab] == "deleted-words"
  		@pagy, @deleted_words = pagy(current_user.entries.deleted(sort))
  	else
		@pagy, @links = pagy(current_user.links.ordered_by_newest)
	end

  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_dashboard-links.html.erb
<div class="profile-links">
	 <div class="button-box">
	 	<div class="sb-container" id="review-all">
	 		<%= link_to "Review all #{pluralize(StudyRecord.where("due < ?", Time.now).count, 'word') }", study_sets_path, class: "card-button" %>
		</div>
	 </div>
	 <% @links.each_with_index do |link, index| %>
	 <div class="profile-link">
	 	<div class="link-icon">
	 		<%= image_tag link.source.image %>
	 	</div>
	 	<div class="link-text">
			<div class="link-header">
				<h4>
			  		<%= link_to link.title, clicks_path(:link => link.id), :method => :post %>
				</h4>
			</div>
			<div class="dropbtn link-menu" id="link-dropdown">
				<span>&#8942;</span>				
				<div class="link-dropdown" id="myDropdown">
					<ul>
						<li>
							<a href="<%= link_entries_path(link.id, :edit => true) %>"><%= image_tag "list", class: "link-menu-icon" %>Edit list</a>
						</li>
						<li>
							<%= link_to link, method: "delete" do %>
								<%= image_tag "trashcan", class: "link-menu-icon" %>Delete list
							<% end %>
						</li>
					</ul>
				</div>
			</div>

			<div class="btn-group" role="group"  aria-label="Links">
			  	<% study_set = link.study_sets.find_by(user_id: current_user.id) %>
			  	<div class="link-word-count">
				  <% if !study_set.nil? %>
				  	<%= pluralize(study_set.study_records.where("due < ?", Time.now).count, 'word') %> due
				  <% end %>
				</div>
			  	<% if !study_set.nil? %>
			  		<%= link_to "Review Now", study_set_path(study_set), class: "card-button" %>
			  	<% end %>
			</div>
		</div>
	</div>
	<% end %>
</div>

app/views/users/_deleted-words.html.erb
<div class="deleted-words">
	<table>
		<thead>
		  <tr>
		    <th colspan="2">Word</th>
		    <th>Definition</th>
		    <th>		    	
		    	<div class="sort-dropdown">
		    		<button class="dropbtn">Sort &#9660;</button>
		    		<div id="deleteOrder" class="dropdown-content">
		    			<%= active_link_to "Latest", user_path(current_user, tab: "deleted-words", sort: "study_records.updated_at DESC"), active: { tab: "deleted-words" } %>
		    			<%= active_link_to "Oldest", user_path(current_user, tab: "deleted-words", sort: "study_records.updated_at ASC"), active: { tab: "deleted-words" } %>
		    			<a href="#">あ→ん</a>
		    			<a href="#">ん→あ</a>
		    		</div>
		    	</div>
		    </th>
		  </tr>
		</thead>
		<tbody>
		  <% @deleted_words.each_with_index do |entry, idx| %>
		    <tr class="main-entry <%= "striped" if (idx % 2) == 0 %>" id="entry-<%= entry.id %>">
		   	<!-- If the reading is different from the base word, the base word probably has kanji and needs a tooltip that displays it. -->
		    <td colspan="2" class="word">
			    <% if entry.base_word == entry.reading %>
			      <%= entry.base_word %>
			    <% else %>			    
			      <span class="tooltip"><%= entry.base_word %><span class="tooltiptext"><%= entry.reading %></span></span>
			    <% end %>
			</td>
		      <td><%= entry.definition %><%= entry.secondaries.count > 0 ? raw(" (<span class='alt-tab' id='tab-#{entry.id}'>Alternative definitions</span>)") : "" %></td>
		      <td class="master-col"><%= link_to 'Un-Master', master_study_records_path(study_record: {entry_id: entry.id}), 
		      	method: :post, class: "master_entry_link", tabindex: '0', 
		      	data: { entryid: entry.id} , remote: true %></td>
		    </tr>
		    <% if entry.secondaries.count > 0 %>
		    	<% entry.secondaries.each do |entry| %>

		    		<tr class="tab-alt-content nav-<%= entry.primary_id %>" id="entry-<%= entry.id %>">
						<td></td>
						<td>				    
							<% if entry.base_word == entry.reading %>
			      				<%= entry.base_word %>
			    			<% else %>			    
			      				<span class="tooltip"><%= entry.base_word %><span class="tooltiptext"><%= entry.reading %></span></span>
			    			<% end %>
			    		</td>
						<td><%= entry.definition %></td>
						<td class="master-col"><a data-entry-id="<%= entry.id %>" class="master_entry_link" tabindex="0">Un-Master</a></td>
					</tr>
				
		    	<% end %>
			<% end %>
		  <% end %>
		</tbody>
	</table>
	<%== pagy_nav(@pagy) %>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="profile-sidebar">
	<div class="sidebar-head">
		<div class="gravatar-avatar">
			<%= image_tag current_user.gravatar_url(:size => 200), :class => "grav-img" %>
		</div>
		<div class="user-email">
			<%= current_user.email %>
		</div>
		<div class="user-stats">
			<div class="stat-col">
				<p class="stat-numbers"><%= @total_words %></p>
				<p>Words learned</p>
			</div>
			<div class="stat-col">
				<p class="stat-numbers"><%= @article_count %></p>
				<p>Articles read</p>
			</div>		
		</div>
	</div>
	<div class="dashboard-tab">
			<%= active_link_to "My Articles", user_path(current_user), active: :exact %>
	</div>
	<div class="dashboard-tab">
			<%= active_link_to "Mastered Words", user_path(current_user, tab: "deleted-words"), active: { tab: "deleted-words" } %>
	</div>

</div>
<% if params[:tab] == "deleted-words" %>
	<%= render partial: "deleted-words" %>
<% else %>
	<%= render partial: "dashboard-links" %>
<% end %> 


<%= javascript_pack_tag 'alt-tab-shower', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'dropdown-menu', 'data-turbolinks-track': 'reload' %>